-module(i2p_siphash_tests).

%% Reference vectors from the official veorq/SipHash implementation
%% (siphash.c), generated by compiling and running the reference with
%% key = bytes 0x00..0x0f and message = bytes 0..len-1. Covers every
%% tail length 0..7, the 8-byte block boundary, and multiple blocks.

-include_lib("eunit/include/eunit.hrl").

-define(KEY, list_to_binary(lists:seq(0, 15))).

seq_bytes(Len) -> list_to_binary(lists:seq(0, Len - 1)).

hexl(Bin) -> string:lowercase(binary_to_list(binary:encode_hex(Bin))).

vectors() ->
    [
        {0, "310e0edd47db6f72", "a3817f04ba25a8e66df67214c7550293"},
        {1, "fd67dc93c539f874", "da87c1d86b99af44347659119b22fc45"},
        {2, "5a4fa9d909806c0d", "8177228da4a45dc7fca38bdef60affe4"},
        {3, "2d7efbd796666785", "9c70b60c5267a94e5f33b6b02985ed51"},
        {4, "b7877127e09427cf", "f88164c12d9c8faf7d0f6e7c7bcd5579"},
        {5, "8da699cd64557618", "1368875980776f8854527a07690e9627"},
        {6, "cee3fe586e46c9cb", "14eeca338b208613485ea0308fd7a15e"},
        {7, "37d1018bf50002ab", "a1f1ebbed8dbc153c0b84aa61ff08239"},
        {8, "6224939a79f5f593", "3b62a9ba6258f5610f83e264f31497b4"},
        {9, "b0e4a90bdf82009e", "264499060ad9baabc47f8b02bb6d71ed"},
        {10, "f3b9dd94c5bb5d7a", "00110dc378146956c95447d3f3d0fbba"},
        {11, "a7ad6b22462fb3f4", "0151c568386b6677a2b4dc6f81e5dc18"},
        {12, "fbe50e86bc8f1e75", "d626b266905ef35882634df68532c125"},
        {13, "903d84c02756ea14", "9869e247e9c08b10d029934fc4b952f7"},
        {14, "eef27a8e90ca23f7", "31fcefac66d7de9c7ec7485fe4494902"},
        {15, "e545be4961ca29a1", "5493e99933b0a8117e08ec0f97cfc3d9"},
        {16, "db9bc2577fcc2a3f", "6ee2a4ca67b054bbfd3315bf85230577"},
        {17, "9447be2cf5e99a69", "473d06e8738db89854c066c47ae47740"},
        {24, "94af49f6c650adb8", "2db479ae78bd50d8882a8a178a6132ad"},
        {31, "42c341d8fa92d832", "2939b0183223fafc1723de4f52c43d35"},
        {32, "ce7cf2722f512771", "7c3956ca5eeafc3e363e9d556546eb68"},
        {33, "e37859f94623f3a7", "77c6077146f01c32b6b69d5f4ea9ffcf"},
        {63, "724506eb4c328a95", "5150d1772f50834a503e069a973fbd7c"},
        {64, "d8ca02850bc4d2ac", "1eaf077dc0d4cd3f8cad4d383658a74b"},
        {65, "2459a291dbbeb636", "02233e98fe91e1c8220dca0d285261ef"}
    ].

vectors_test() ->
    lists:foreach(
        fun({Len, Ref64, Ref128}) ->
            Data = seq_bytes(Len),
            ?assertEqual(Ref64, hexl(i2p_siphash:hash_le(Data, ?KEY))),
            ?assertEqual(Ref128, hexl(i2p_siphash:hash_128_le(Data, ?KEY)))
        end,
        vectors()
    ),
    ok.

key_sensitivity_test() ->
    %% Flipping a single key bit must change both outputs.
    Data = <<16#00, 16#01, 16#02, 16#03, 16#04, 16#05, 16#06, 16#07>>,
    K1 = ?KEY,
    <<H:8, Rest/binary>> = K1,
    K2 = <<(H bxor 1):8, Rest/binary>>,
    ?assertNotEqual(i2p_siphash:hash(Data, K1), i2p_siphash:hash(Data, K2)),
    ?assertNotEqual(i2p_siphash:hash_128(Data, K1), i2p_siphash:hash_128(Data, K2)).

bad_key_test() ->
    ?assertError(function_clause, i2p_siphash:hash(<<1, 2, 3>>, <<1, 2, 3>>)).
